### ISSUE TITLE
auto requires c++14

### ISSUE THREAD

**Issue by aelam** [polaris/generic-object-factory#1]
If it can support a lower version of C++ ?

**Comment by polaris** [comment]
Something similar should be possible with C++11 and probably even older standard. C++14 makes it more elegant I suppose. Check this branch: [https://github.com/polaris/generic-object-factory/tree/c++11](https://github.com/polaris/generic-object-factory/tree/c++11)

Does that help you?

By the way: auto does not require C++14. Though the way I used it does. Does your compiler support C++11?

**Comment by aelam** [comment]
Thank you very much!!

My origin default setting(Xcode project) is c++11, it doesn't work.
Then I change to c++14 with the c++ library, it works!!
So my conclusion is
* `auto` requires `C14++`
* `std::make_unique` requires c++ library 

This is my final settings
```
CLANG_CXX_LANGUAGE_STANDARD = "c++14";
CLANG_CXX_LIBRARY = "libc++";
```
